name: 'Run App AbdoulAzizDiop'

on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.201'
      - name: Install OpenSSL 3
        run: sudo apt-get update && sudo apt-get install -y libssl3
      - uses: nuget/setup-nuget@v1
      - name: Nuget Restore
        run: nuget restore GithubActions.sln
      - name: Install dependencies
        run: dotnet restore GithubActions.sln
      - name: Build
        run: msbuild /p:Configuration=Release GithubActions.sln
      - name: Run Unit Tests
        run: |
          mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe \
          ./Tests/bin/Release/Tests.dll \
          --labels=All 
      - name: Run Tests with XML Output
        run: |
          mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe \
          ./Tests/bin/Release/Tests.dll \
          --result=TestResults.xml
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: TestResults.xml