name: 'Run App AbdoulAzizDiop'

on: [push, pull_request]

jobs:
  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.201'
      - name: Install OpenSSL 3
        run: sudo apt-get update && sudo apt-get install -y libssl3
      - uses: nuget/setup-nuget@v1
      - name: Nuget Restore
        run: nuget restore GithubActions.sln
      - name: Install dependencies
        run: dotnet restore GithubActions.sln
      - name: Build
        run: msbuild /p:Configuration=Release GithubActions.sln
      - name: Debug Solution Structure
        run: |
          cat GithubActions.sln | grep "Tests.csproj"  # Check if tests are in solution
      - name: Build
        run: |
          msbuild /p:Configuration=Release ./Tests/Tests.csproj  # Build test project directly
          ls ./Tests/bin/Release  # Verify DLL exists
          - name: Install NUnit 
        run: |
          nuget restore ./Tests/packages.config -PackagesDirectory ./packages
          nuget install NUnit.Console -Version 3.12.0 -OutputDirectory ./packages
      - name: Build Tests
        run: |
          # Restore test project packages
          nuget restore ./Tests/packages.config -PackagesDirectory ./packages
          
          # Build ONLY the test project
          msbuild ./Tests/Tests.csproj /p:Configuration=Release
          
          # Verify DLL was created
          if [ ! -f "./Tests/bin/Release/Tests.dll" ]; then
            echo "::error::Tests.dll not found! Build output:"
            ls -R ./Tests/bin
            exit 1
          fi

      - name: Run Tests
        run: |
          mono ./packages/NUnit.ConsoleRunner.3.*/tools/nunit3-console.exe \
            ./Tests/bin/Release/Tests.dll \
            --noheader \
            --labels=All